spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kosssaa/configuration.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
